export const solid = [
  // solid
  'house',
  'magnifying-glass',
  'user',
  'check',
  'download',
  'image',
  'phone',
  'bars',
  'envelope',
  'star',
  'location-dot',
  'music',
  'wand-magic-sparkles',
  'heart',
  'arrow-right',
  'circle-xmark',
  'bomb',
  'poo',
  'camera-retro',
  'xmark',
  'cloud',
  'comment',
  'caret-up',
  'truck-fast',
  'pen-nib',
  'arrow-up',
  'hippo',
  'face-smile',
  'calendar-days',
  'paperclip',
  'shield-halved',
  'file',
  'bell',
  'cart-shopping',
  'clipboard',
  'filter',
  'circle-info',
  'arrow-up-from-bracket',
  'bolt',
  'car',
  'ghost',
  'mug-hot',
  'circle-user',
  'pen',
  'umbrella',
  'gift',
  'film',
  'list',
  'gear',
  'trash',
  'circle-up',
  'circle-down',
  'inbox',
  'rotate-right',
  'lock',
  'headphones',
  'barcode',
  'tag',
  'book',
  'bookmark',
  'print',
  'camera',
  'font',
  'video',
  'circle-half-stroke',
  'droplet',
  'pen-to-square',
  'share-from-square',
  'plus',
  'minus',
  'share',
  'circle-exclamation',
  'fire',
  'eye',
  'eye-slash',
  'plane',
  'magnet',
  'hand',
  'folder',
  'folder-open',
  'money-bill',
  'thumbs-up',
  'thumbs-down',
  'comments',
  'lemon',
  'key',
  'thumbtack',
  'gears',
  'paper-plane',
  'code',
  'globe',
  'truck',
  'city',
  'ticket',
  'tree',
  'wifi',
  'paint-roller',
  'bicycle',
  'sliders',
  'brush',
  'hashtag',
  'flask',
  'briefcase',
  'compass',
  'dumpster-fire',
  'person',
  'person-dress',
  'address-book',
  'bath',
  'handshake',
  'snowflake',
  'right-to-bracket',
  'earth-americas',
  'cloud-arrow-up',
  'binoculars',
  'palette',
  'layer-group',
  'users',
  'gamepad',
  'business-time',
  'feather',
  'sun',
  'link',
  'pen-fancy',
  'fish',
  'bug',
  'shop',
  'mug-saucer',
  'landmark',
  'poo-storm',
  'chart-simple',
  'shirt',
  'anchor',
  'quote-left',
  'bag-shopping',
  'gauge',
  'code-compare',
  'user-secret',
  'stethoscope',
  'car-side',
  'hand-holding-heart',
  'truck-front',
  'cable-car',
  'mountain-sun',
  'location-pin',
  'info',
  'user-minus',
  'calendar',
  'cart-plus',
  'clock',
  'circle',
  'play',
  'cross',
  'backward',
  'handshake-slash',
  'chevron-up',
  'passport',
  'question',
  'pencil',
  'phone-volume',
  'upload',
  'strikethrough',
  'credit-card',
  'street-view',
  'database',
  'copy',
  'mobile',
  'square',
  'sort',
  'forward',
  'hourglass-start',
  'newspaper',
  'notes-medical',
  'table',
  'building',
  'stop',
  'store',
  'flag',
  'file-excel',
  'network-wired',
  'cash-register',
  'file-export',
  'hand-point-up',
  'angle-up',
  'shield',
  'address-card',
  'expand',
  'flag-checkered',
  'quote-right',
  'tags',
  'server',
  'user-nurse',
  'video-slash',
  'arrow-down',
  'blog',
  'school',
  'file-invoice',
  'rocket',
  'spinner',
  'tty',
  'exclamation',
  'water',
  'registered',
  'signature',
  'laptop',
  'restroom',
  'power-off',
  'sitemap',
  'icons',
  'desktop',
  'moon',
  'calendar-week',
  'pause',
  'file-word',
  'vials',
  'language',
  'door-open',
  'brain',
  'hotel',
  'marker',
  'star-of-life',
  'leaf',
  'walkie-talkie',
  'shower',
  'caret-down',
  'file-import',
  'place-of-worship',
  'wallet',
  'slash',
  'award',
  'toggle-on',
  'ship',
  'chalkboard',
  'hands',
  'signal',
  'motorcycle',
  'arrow-up-right-from-square',
  'audio-description',
  'seedling',
  'closed-captioning',
  'train',
  'arrow-left',
  'wrench',
  'microchip',
  'record-vinyl',
  'trophy',
  'hammer',
  'diamond',
  'robot',
  'file-pdf',
  'hospital',
  'file-contract',
  'square-xmark',
  'square-check',
  'crown',
  'user-plus',
  'virus',
  'child',
  'repeat',
  'cube',
  'copyright',
  'medal',
  'bullseye',
  'mask',
  'circle-check',
  'radio',
  'reply',
  'chair',
  'route',
  'plug',
  'calculator',
  'dragon',
  'certificate',
  'fingerprint',
  'road',
  'crosshairs',
  'heading',
  'percent',
  'user-tie',
  'square-minus',
  'i-cursor',
  'church',
  'joint',
  'comments-dollar',
  'truck-monster',
  'recycle',
  'warehouse',
  'ruler',
  'soap',
  'scroll',
  'coins',
  'wind',
  'baby',
  'lightbulb',
  'voicemail',
  'puzzle-piece',
  'keyboard',
  'clone',
  'eraser',
  'wine-bottle',
  'dice',
  'receipt',
  'ring',
  'unlock',
  'solar-panel',
  'ruler-vertical',
  'circle-notch',
  'people-arrows',
  'dollar-sign',
  'tablet',
  'not-equal',
  'glasses',
  'headset',
  'code-branch',
  'gopuram',
  'images',
  'window-restore',
  'industry',
  'stamp',
  'microphone-slash',
  'cookie-bite',
  'otter',
  'chevron-down',
  'kiwi-bird',
  'viruses',
  'umbrella-beach',
  'subscript',
  'tablets',
  'microphone',
  'border-none',
  'dumbbell',
  'plane-departure',
  'z',
  'yin-yang',
  'yen-sign',
  'y',
  'xmarks-lines',
  'x-ray',
  'x',
  'worm',
  'won-sign',
  'wine-glass-empty',
  'wine-glass',
  'window-minimize',
  'window-maximize',
  'whiskey-glass',
  'wheelchair-move',
  'wheelchair',
  'wheat-awn-circle-exclamation',
  'wheat-awn',
  'weight-scale',
  'weight-hanging',
  'wave-square',
  'water-ladder',
  'wand-sparkles',
  'wand-magic',
  'w',
  'vr-cardboard',
  'volume-xmark',
  'volume-off',
  'volume-low',
  'volume-high',
  'volleyball',
  'volcano',
  'virus-slash',
  'virus-covid-slash',
  'virus-covid',
  'vihara',
  'vial-virus',
  'vial-circle-check',
  'vial',
  'vest-patches',
  'vest',
  'venus-mars',
  'venus-double',
  'venus',
  'vector-square',
  'vault',
  'van-shuttle',
  'v',
  'utensils',
  'users-viewfinder',
  'users-slash',
  'users-rectangle',
  'users-rays',
  'users-line',
  'users-gear',
  'users-between-lines',
  'user-xmark',
  'user-tag',
  'user-slash',
  'user-shield',
  'user-pen',
  'user-ninja',
  'user-lock',
  'user-large-slash',
  'user-large',
  'user-injured',
  'user-group',
  'user-graduate',
  'user-gear',
  'user-doctor',
  'user-clock',
  'user-check',
  'user-astronaut',
  'up-right-from-square',
  'up-right-and-down-left-from-center',
  'up-long',
  'up-down-left-right',
  'up-down',
  'unlock-keyhole',
  'universal-access',
  'underline',
  'u',
  'tv',
  'turn-up',
  'turn-down',
  'turkish-lira-sign',
  'truck-ramp-box',
  'truck-plane',
  'truck-pickup',
  'truck-moving',
  'truck-medical',
  'truck-field-un',
  'truck-field',
  'truck-droplet',
  'truck-arrow-right',
  'trowel-bricks',
  'trowel',
  'triangle-exclamation',
  'tree-city',
  'trash-can-arrow-up',
  'trash-can',
  'trash-arrow-up',
  'transgender',
  'train-tram',
  'train-subway',
  'trailer',
  'traffic-light',
  'trademark',
  'tractor',
  'tower-observation',
  'tower-cell',
  'tower-broadcast',
  'tornado',
  'torii-gate',
  'tooth',
  'toolbox',
  'toilets-portable',
  'toilet-portable',
  'toilet-paper-slash',
  'toilet-paper',
  'toilet',
  'toggle-off',
  'timeline',
  'ticket-simple',
  'thermometer',
  'text-width',
  'text-slash',
  'text-height',
  'terminal',
  'tents',
  'tent-arrows-down',
  'tent-arrow-turn-left',
  'tent-arrow-left-right',
  'tent-arrow-down-to-line',
  'tent',
  'tenge-sign',
  'temperature-three-quarters',
  'temperature-quarter',
  'temperature-low',
  'temperature-high',
  'temperature-half',
  'temperature-full',
  'temperature-empty',
  'temperature-arrow-up',
  'temperature-arrow-down',
  'teeth-open',
  'teeth',
  'taxi',
  'tarp-droplet',
  'tarp',
  'tape',
  'tachograph-digital',
  'tablet-screen-button',
  'tablet-button',
  'table-tennis-paddle-ball',
  'table-list',
  'table-columns',
  'table-cells-large',
  'table-cells',
  't',
  'syringe',
  'synagogue',
  'swatchbook',
  'superscript',
  'sun-plant-wilt',
  'suitcase-rolling',
  'suitcase-medical',
  'suitcase',
  'stroopwafel',
  'store-slash',
  'stopwatch-20',
  'stopwatch',
  'sterling-sign',
  'star-of-david',
  'star-half-stroke',
  'star-half',
  'star-and-crescent',
  'stapler',
  'stairs',
  'staff-snake',
  'square-virus',
  'square-up-right',
  'square-share-nodes',
  'square-rss',
  'square-root-variable',
  'square-poll-vertical',
  'square-poll-horizontal',
  'square-plus',
  'square-phone-flip',
  'square-phone',
  'square-person-confined',
  'square-pen',
  'square-parking',
  'square-nfi',
  'square-h',
  'square-full',
  'square-envelope',
  'square-caret-up',
  'square-caret-right',
  'square-caret-left',
  'square-caret-down',
  'square-arrow-up-right',
  'spray-can-sparkles',
  'spray-can',
  'spoon',
  'splotch',
  'spider',
  'spell-check',
  'spaghetti-monster-flying',
  'spa',
  'sort-up',
  'sort-down',
  'socks',
  'snowplow',
  'snowman',
  'smoking',
  'smog',
  'sleigh',
  'skull-crossbones',
  'skull',
  'sink',
  'sim-card',
  'signs-post',
  'sign-hanging',
  'shuttle-space',
  'shuffle',
  'shrimp',
  'shop-slash',
  'shop-lock',
  'shoe-prints',
  'shield-virus',
  'shield-heart',
  'shield-dog',
  'shield-cat',
  'shekel-sign',
  'sheet-plastic',
  'share-nodes',
  'shapes',
  'section',
  'sd-card',
  'scroll-torah',
  'screwdriver-wrench',
  'screwdriver',
  'scissors',
  'school-lock',
  'school-flag',
  'school-circle-xmark',
  'school-circle-exclamation',
  'school-circle-check',
  'scale-unbalanced-flip',
  'scale-unbalanced',
  'scale-balanced',
  'satellite-dish',
  'satellite',
  'sailboat',
  'sack-xmark',
  'sack-dollar',
  's',
  'rupiah-sign',
  'rupee-sign',
  'ruler-horizontal',
  'ruler-combined',
  'rug',
  'ruble-sign',
  'rss',
  'rotate-left',
  'rotate',
  'road-spikes',
  'road-lock',
  'road-circle-xmark',
  'road-circle-exclamation',
  'road-circle-check',
  'road-bridge',
  'road-barrier',
  'right-long',
  'right-left',
  'right-from-bracket',
  'ribbon',
  'retweet',
  'republican',
  'reply-all',
  'rectangle-xmark',
  'rectangle-list',
  'rectangle-ad',
  'ranking-star',
  'rainbow',
  'radiation',
  'r',
  'qrcode',
  'q',
  'pump-soap',
  'pump-medical',
  'prescription-bottle-medical',
  'prescription-bottle',
  'prescription',
  'poop',
  'podcast',
  'plus-minus',
  'plug-circle-xmark',
  'plug-circle-plus',
  'plug-circle-minus',
  'plug-circle-exclamation',
  'plug-circle-check',
  'plug-circle-bolt',
  'plate-wheat',
  'plant-wilt',
  'plane-up',
  'plane-slash',
  'plane-lock',
  'plane-circle-xmark',
  'plane-circle-exclamation',
  'plane-circle-check',
  'plane-arrival',
  'pizza-slice',
  'pills',
  'piggy-bank',
  'photo-film',
  'phone-slash',
  'phone-flip',
  'peso-sign',
  'peseta-sign',
  'person-walking-with-cane',
  'person-walking-luggage',
  'person-walking-dashed-line-arrow-right',
  'person-walking-arrow-right',
  'person-walking-arrow-loop-left',
  'person-walking',
  'person-through-window',
  'person-swimming',
  'person-snowboarding',
  'person-skiing-nordic',
  'person-skiing',
  'person-skating',
  'person-shelter',
  'person-running',
  'person-rifle',
  'person-rays',
  'person-pregnant',
  'person-praying',
  'person-military-to-person',
  'person-military-rifle',
  'person-military-pointing',
  'person-hiking',
  'person-harassing',
  'person-half-dress',
  'person-falling-burst',
  'person-falling',
  'person-drowning',
  'person-dress-burst',
  'person-dots-from-line',
  'person-digging',
  'person-circle-xmark',
  'person-circle-plus',
  'person-circle-minus',
  'person-circle-exclamation',
  'person-circle-check',
  'person-chalkboard',
  'person-cane',
  'person-burst',
  'person-breastfeeding',
  'person-booth',
  'person-biking',
  'person-arrow-up-from-line',
  'person-arrow-down-to-line',
  'pepper-hot',
  'people-roof',
  'people-robbery',
  'people-pulling',
  'people-line',
  'people-group',
  'people-carry-box',
  'pen-ruler',
  'pen-clip',
  'peace',
  'paw',
  'paste',
  'paragraph',
  'parachute-box',
  'panorama',
  'pallet',
  'paintbrush',
  'pager',
  'p',
  'outdent',
  'om',
  'oil-well',
  'oil-can',
  'object-ungroup',
  'object-group',
  'o',
  'note-sticky',
  'neuter',
  'naira-sign',
  'n',
  'mountain-city',
  'mountain',
  'mound',
  'mosquito-net',
  'mosquito',
  'mosque',
  'mortar-pestle',
  'monument',
  'money-check-dollar',
  'money-check',
  'money-bills',
  'money-bill-wheat',
  'money-bill-wave',
  'money-bill-trend-up',
  'money-bill-transfer',
  'money-bill-1-wave',
  'money-bill-1',
  'mobile-screen-button',
  'mobile-screen',
  'mobile-retro',
  'mobile-button',
  'mitten',
  'minimize',
  'mill-sign',
  'microscope',
  'microphone-lines-slash',
  'microphone-lines',
  'meteor',
  'message',
  'mercury',
  'menorah',
  'memory',
  'maximize',
  'mattress-pillow',
  'masks-theater',
  'mask-ventilator',
  'mask-face',
  'martini-glass-empty',
  'martini-glass-citrus',
  'martini-glass',
  'mars-stroke-up',
  'mars-stroke-right',
  'mars-stroke',
  'mars-double',
  'mars-and-venus-burst',
  'mars-and-venus',
  'mars',
  'map-pin',
  'map-location-dot',
  'map-location',
  'map',
  'manat-sign',
  'magnifying-glass-plus',
  'magnifying-glass-minus',
  'magnifying-glass-location',
  'magnifying-glass-dollar',
  'magnifying-glass-chart',
  'magnifying-glass-arrow-right',
  'm',
  'lungs-virus',
  'lungs',
  'locust',
  'lock-open',
  'location-pin-lock',
  'location-crosshairs',
  'location-arrow',
  'litecoin-sign',
  'list-ul',
  'list-ol',
  'list-check',
  'lira-sign',
  'link-slash',
  'lines-leaning',
  'life-ring',
  'less-than-equal',
  'less-than',
  'left-right',
  'left-long',
  'lari-sign',
  'laptop-medical',
  'laptop-file',
  'laptop-code',
  'landmark-flag',
  'landmark-dome',
  'land-mine-on',
  'l',
  'kitchen-set',
  'kit-medical',
  'kip-sign',
  'khanda',
  'kaaba',
  'k',
  'jug-detergent',
  'jet-fighter-up',
  'jet-fighter',
  'jedi',
  'jar-wheat',
  'jar',
  'j',
  'italic',
  'infinity',
  'indian-rupee-sign',
  'indent',
  'image-portrait',
  'igloo',
  'id-card-clip',
  'id-card',
  'id-badge',
  'icicles',
  'ice-cream',
  'i',
  'hurricane',
  'hryvnia-sign',
  'house-user',
  'house-tsunami',
  'house-signal',
  'house-medical-flag',
  'house-medical-circle-xmark',
  'house-medical-circle-exclamation',
  'house-medical-circle-check',
  'house-medical',
  'house-lock',
  'house-laptop',
  'house-flood-water-circle-arrow-right',
  'house-flood-water',
  'house-flag',
  'house-fire',
  'house-crack',
  'house-circle-xmark',
  'house-circle-exclamation',
  'house-circle-check',
  'house-chimney-window',
  'house-chimney-user',
  'house-chimney-medical',
  'house-chimney-crack',
  'house-chimney',
  'hourglass-half',
  'hourglass-end',
  'hourglass',
  'hotdog',
  'hot-tub-person',
  'hospital-user',
  'horse-head',
  'horse',
  'holly-berry',
  'hockey-puck',
  'hill-rockslide',
  'hill-avalanche',
  'highlighter',
  'helmet-un',
  'helmet-safety',
  'helicopter-symbol',
  'helicopter',
  'heart-pulse',
  'heart-crack',
  'heart-circle-xmark',
  'heart-circle-plus',
  'heart-circle-minus',
  'heart-circle-exclamation',
  'heart-circle-check',
  'heart-circle-bolt',
  'headphones-simple',
  'head-side-virus',
  'head-side-mask',
  'head-side-cough-slash',
  'head-side-cough',
  'hat-wizard',
  'hat-cowboy-side',
  'hat-cowboy',
  'hard-drive',
  'hanukiah',
  'handshake-simple-slash',
  'handshake-simple',
  'handshake-angle',
  'hands-praying',
  'hands-holding-circle',
  'hands-holding-child',
  'hands-holding',
  'hands-clapping',
  'hands-bubbles',
  'hands-bound',
  'hands-asl-interpreting',
  'handcuffs',
  'hand-spock',
  'hand-sparkles',
  'hand-scissors',
  'hand-pointer',
  'hand-point-right',
  'hand-point-left',
  'hand-point-down',
  'hand-peace',
  'hand-middle-finger',
  'hand-lizard',
  'hand-holding-medical',
  'hand-holding-hand',
  'hand-holding-droplet',
  'hand-holding-dollar',
  'hand-holding',
  'hand-fist',
  'hand-dots',
  'hand-back-fist',
  'hamsa',
  'h',
  'gun',
  'guitar',
  'guarani-sign',
  'group-arrows-rotate',
  'grip-vertical',
  'grip-lines-vertical',
  'grip-lines',
  'grip',
  'greater-than-equal',
  'greater-than',
  'graduation-cap',
  'golf-ball-tee',
  'glass-water-droplet',
  'glass-water',
  'gifts',
  'genderless',
  'gem',
  'gavel',
  'gauge-simple-high',
  'gauge-simple',
  'gauge-high',
  'gas-pump',
  'g',
  'futbol',
  'frog',
  'franc-sign',
  'forward-step',
  'forward-fast',
  'football',
  'font-awesome',
  'folder-tree',
  'folder-plus',
  'folder-minus',
  'folder-closed',
  'florin-sign',
  'floppy-disk',
  'flask-vial',
  'flag-usa',
  'fish-fins',
  'fire-flame-simple',
  'fire-flame-curved',
  'fire-extinguisher',
  'fire-burner',
  'filter-circle-xmark',
  'filter-circle-dollar',
  'fill-drip',
  'fill',
  'file-zipper',
  'file-waveform',
  'file-video',
  'file-signature',
  'file-shield',
  'file-prescription',
  'file-powerpoint',
  'file-pen',
  'file-medical',
  'file-lines',
  'file-invoice-dollar',
  'file-image',
  'file-csv',
  'file-code',
  'file-circle-xmark',
  'file-circle-question',
  'file-circle-plus',
  'file-circle-minus',
  'file-circle-exclamation',
  'file-circle-check',
  'file-audio',
  'file-arrow-up',
  'file-arrow-down',
  'ferry',
  'feather-pointed',
  'fax',
  'faucet-drip',
  'faucet',
  'fan',
  'face-tired',
  'face-surprise',
  'face-smile-wink',
  'face-smile-beam',
  'face-sad-tear',
  'face-sad-cry',
  'face-rolling-eyes',
  'face-meh-blank',
  'face-meh',
  'face-laugh-wink',
  'face-laugh-squint',
  'face-laugh-beam',
  'face-laugh',
  'face-kiss-wink-heart',
  'face-kiss-beam',
  'face-kiss',
  'face-grin-wink',
  'face-grin-wide',
  'face-grin-tongue-wink',
  'face-grin-tongue-squint',
  'face-grin-tongue',
  'face-grin-tears',
  'face-grin-stars',
  'face-grin-squint-tears',
  'face-grin-squint',
  'face-grin-hearts',
  'face-grin-beam-sweat',
  'face-grin-beam',
  'face-grin',
  'face-grimace',
  'face-frown-open',
  'face-frown',
  'face-flushed',
  'face-dizzy',
  'face-angry',
  'f',
  'eye-low-vision',
  'eye-dropper',
  'explosion',
  'euro-sign',
  'ethernet',
  'equals',
  'envelopes-bulk',
  'envelope-open-text',
  'envelope-open',
  'envelope-circle-check',
  'ellipsis-vertical',
  'ellipsis',
  'elevator',
  'eject',
  'egg',
  'earth-oceania',
  'earth-europe',
  'earth-asia',
  'earth-africa',
  'ear-listen',
  'ear-deaf',
  'e',
  'dungeon',
  'dumpster',
  'drumstick-bite',
  'drum-steelpan',
  'drum',
  'droplet-slash',
  'draw-polygon',
  'down-long',
  'down-left-and-up-right-to-center',
  'dove',
  'door-closed',
  'dong-sign',
  'dolly',
  'dog',
  'dna',
  'divide',
  'display',
  'disease',
  'dice-two',
  'dice-three',
  'dice-six',
  'dice-one',
  'dice-four',
  'dice-five',
  'dice-d6',
  'dice-d20',
  'diamond-turn-right',
  'diagram-successor',
  'diagram-project',
  'diagram-predecessor',
  'diagram-next',
  'dharmachakra',
  'democrat',
  'delete-left',
  'd',
  'cubes-stacked',
  'cubes',
  'cruzeiro-sign',
  'crutch',
  'crow',
  'crop-simple',
  'crop',
  'cow',
  'couch',
  'cookie',
  'computer-mouse',
  'computer',
  'compress',
  'compass-drafting',
  'compact-disc',
  'comment-sms',
  'comment-slash',
  'comment-medical',
  'comment-dots',
  'comment-dollar',
  'colon-sign',
  'code-pull-request',
  'code-merge',
  'code-fork',
  'code-commit',
  'clover',
  'cloud-sun-rain',
  'cloud-sun',
  'cloud-showers-water',
  'cloud-showers-heavy',
  'cloud-rain',
  'cloud-moon-rain',
  'cloud-moon',
  'cloud-meatball',
  'cloud-bolt',
  'cloud-arrow-down',
  'clock-rotate-left',
  'clipboard-user',
  'clipboard-question',
  'clipboard-list',
  'clipboard-check',
  'clapperboard',
  'circle-stop',
  'circle-right',
  'circle-radiation',
  'circle-question',
  'circle-plus',
  'circle-play',
  'circle-pause',
  'circle-nodes',
  'circle-minus',
  'circle-left',
  'circle-h',
  'circle-dot',
  'circle-dollar-to-slot',
  'circle-chevron-up',
  'circle-chevron-right',
  'circle-chevron-left',
  'circle-chevron-down',
  'circle-arrow-up',
  'circle-arrow-right',
  'circle-arrow-left',
  'circle-arrow-down',
  'children',
  'child-rifle',
  'child-reaching',
  'child-dress',
  'chevron-right',
  'chevron-left',
  'chess-rook',
  'chess-queen',
  'chess-pawn',
  'chess-knight',
  'chess-king',
  'chess-board',
  'chess-bishop',
  'chess',
  'cheese',
  'check-to-slot',
  'check-double',
  'chart-pie',
  'chart-line',
  'chart-gantt',
  'chart-column',
  'chart-bar',
  'chart-area',
  'charging-station',
  'champagne-glasses',
  'chalkboard-user',
  'cent-sign',
  'cedi-sign',
  'cat',
  'cart-flatbed-suitcase',
  'cart-flatbed',
  'cart-arrow-down',
  'carrot',
  'caret-right',
  'caret-left',
  'caravan',
  'car-tunnel',
  'car-rear',
  'car-on',
  'car-burst',
  'car-battery',
  'capsules',
  'cannabis',
  'candy-cane',
  'campground',
  'camera-rotate',
  'calendar-xmark',
  'calendar-plus',
  'calendar-minus',
  'calendar-day',
  'calendar-check',
  'cake-candles',
  'c',
  'bus-simple',
  'bus',
  'burst',
  'burger',
  'bullhorn',
  'building-wheat',
  'building-user',
  'building-un',
  'building-shield',
  'building-ngo',
  'building-lock',
  'building-flag',
  'building-columns',
  'building-circle-xmark',
  'building-circle-exclamation',
  'building-circle-check',
  'building-circle-arrow-right',
  'bugs',
  'bug-slash',
  'bucket',
  'broom-ball',
  'broom',
  'briefcase-medical',
  'bridge-water',
  'bridge-lock',
  'bridge-circle-xmark',
  'bridge-circle-exclamation',
  'bridge-circle-check',
  'bridge',
  'bread-slice',
  'brazilian-real-sign',
  'braille',
  'boxes-stacked',
  'boxes-packing',
  'box-tissue',
  'box-open',
  'box-archive',
  'box',
  'bowling-ball',
  'bowl-rice',
  'bowl-food',
  'bottle-water',
  'bottle-droplet',
  'bore-hole',
  'border-top-left',
  'border-all',
  'book-tanakh',
  'book-skull',
  'book-quran',
  'book-open-reader',
  'book-open',
  'book-medical',
  'book-journal-whills',
  'book-bookmark',
  'book-bible',
  'book-atlas',
  'bong',
  'bone',
  'bolt-lightning',
  'bold',
  'blender-phone',
  'blender',
  'bitcoin-sign',
  'biohazard',
  'bezier-curve',
  'bell-slash',
  'bell-concierge',
  'beer-mug-empty',
  'bed-pulse',
  'bed',
  'battery-three-quarters',
  'battery-quarter',
  'battery-half',
  'battery-full',
  'battery-empty',
  'basketball',
  'basket-shopping',
  'baseball-bat-ball',
  'baseball',
  'bars-staggered',
  'bars-progress',
  'bandage',
  'ban-smoking',
  'ban',
  'baht-sign',
  'bahai',
  'bacterium',
  'bacteria',
  'bacon',
  'backward-step',
  'backward-fast',
  'baby-carriage',
  'b',
  'austral-sign',
  'atom',
  'at',
  'asterisk',
  'arrows-up-to-line',
  'arrows-up-down-left-right',
  'arrows-up-down',
  'arrows-turn-to-dots',
  'arrows-turn-right',
  'arrows-to-eye',
  'arrows-to-dot',
  'arrows-to-circle',
  'arrows-split-up-and-left',
  'arrows-spin',
  'arrows-rotate',
  'arrows-left-right-to-line',
  'arrows-left-right',
  'arrows-down-to-people',
  'arrows-down-to-line',
  'arrow-up-z-a',
  'arrow-up-wide-short',
  'arrow-up-short-wide',
  'arrow-up-right-dots',
  'arrow-up-long',
  'arrow-up-from-water-pump',
  'arrow-up-from-ground-water',
  'arrow-up-a-z',
  'arrow-up-9-1',
  'arrow-up-1-9',
  'arrow-turn-up',
  'arrow-turn-down',
  'arrow-trend-up',
  'arrow-trend-down',
  'arrow-rotate-right',
  'arrow-rotate-left',
  'arrow-right-to-city',
  'arrow-right-to-bracket',
  'arrow-right-long',
  'arrow-right-from-bracket',
  'arrow-right-arrow-left',
  'arrow-pointer',
  'arrow-left-long',
  'arrow-down-z-a',
  'arrow-down-wide-short',
  'arrow-down-up-lock',
  'arrow-down-up-across-line',
  'arrow-down-short-wide',
  'arrow-down-long',
  'arrow-down-a-z',
  'arrow-down-9-1',
  'arrow-down-1-9',
  'archway',
  'apple-whole',
  'ankh',
  'angles-up',
  'angles-right',
  'angles-left',
  'angles-down',
  'angle-right',
  'angle-left',
  'angle-down',
  'anchor-lock',
  'anchor-circle-xmark',
  'anchor-circle-exclamation',
  'anchor-circle-check',
  'align-right',
  'align-left',
  'align-justify',
  'align-center',
  'a',
  '9',
  '8',
  '7',
  '6',
  '5',
  '4',
  '3',
  '2',
  '1',
  '0'
] as const;
export const regular = [
  // regular
  'fa-regular fa-user',
  'fa-regular fa-image',
  'fa-regular fa-envelope',
  'fa-regular fa-star',
  'fa-regular fa-heart',
  'fa-regular fa-circle-xmark',
  'fa-regular fa-comment',
  'fa-regular fa-face-smile',
  'fa-regular fa-calendar-days',
  'fa-regular fa-file',
  'fa-regular fa-bell',
  'fa-regular fa-clipboard',
  'fa-regular fa-circle-user',
  'fa-regular fa-circle-up',
  'fa-regular fa-circle-down',
  'fa-regular fa-bookmark',
  'fa-regular fa-pen-to-square',
  'fa-regular fa-share-from-square',
  'fa-regular fa-eye',
  'fa-regular fa-eye-slash',
  'fa-regular fa-hand',
  'fa-regular fa-folder',
  'fa-regular fa-folder-open',
  'fa-regular fa-thumbs-up',
  'fa-regular fa-thumbs-down',
  'fa-regular fa-comments',
  'fa-regular fa-lemon',
  'fa-regular fa-paper-plane',
  'fa-regular fa-compass',
  'fa-regular fa-address-book',
  'fa-regular fa-handshake',
  'fa-regular fa-snowflake',
  'fa-regular fa-sun',
  'fa-regular fa-calendar',
  'fa-regular fa-clock',
  'fa-regular fa-circle',
  'fa-regular fa-credit-card',
  'fa-regular fa-copy',
  'fa-regular fa-square',
  'fa-regular fa-newspaper',
  'fa-regular fa-building',
  'fa-regular fa-flag',
  'fa-regular fa-file-excel',
  'fa-regular fa-hand-point-up',
  'fa-regular fa-address-card',
  'fa-regular fa-registered',
  'fa-regular fa-moon',
  'fa-regular fa-file-word',
  'fa-regular fa-closed-captioning',
  'fa-regular fa-file-pdf',
  'fa-regular fa-hospital',
  'fa-regular fa-square-check',
  'fa-regular fa-copyright',
  'fa-regular fa-circle-check',
  'fa-regular fa-square-minus',
  'fa-regular fa-lightbulb',
  'fa-regular fa-keyboard',
  'fa-regular fa-clone',
  'fa-regular fa-images',
  'fa-regular fa-window-restore',
  'fa-regular fa-window-minimize',
  'fa-regular fa-window-maximize',
  'fa-regular fa-trash-can',
  'fa-regular fa-star-half-stroke',
  'fa-regular fa-star-half',
  'fa-regular fa-square-plus',
  'fa-regular fa-square-full',
  'fa-regular fa-square-caret-up',
  'fa-regular fa-square-caret-right',
  'fa-regular fa-square-caret-left',
  'fa-regular fa-square-caret-down',
  'fa-regular fa-rectangle-xmark',
  'fa-regular fa-rectangle-list',
  'fa-regular fa-paste',
  'fa-regular fa-object-ungroup',
  'fa-regular fa-object-group',
  'fa-regular fa-note-sticky',
  'fa-regular fa-money-bill-1',
  'fa-regular fa-message',
  'fa-regular fa-map',
  'fa-regular fa-life-ring',
  'fa-regular fa-id-card',
  'fa-regular fa-id-badge',
  'fa-regular fa-hourglass-half',
  'fa-regular fa-hourglass',
  'fa-regular fa-hard-drive',
  'fa-regular fa-hand-spock',
  'fa-regular fa-hand-scissors',
  'fa-regular fa-hand-pointer',
  'fa-regular fa-hand-point-right',
  'fa-regular fa-hand-point-left',
  'fa-regular fa-hand-point-down',
  'fa-regular fa-hand-peace',
  'fa-regular fa-hand-lizard',
  'fa-regular fa-hand-back-fist',
  'fa-regular fa-gem',
  'fa-regular fa-futbol',
  'fa-regular fa-font-awesome',
  'fa-regular fa-folder-closed',
  'fa-regular fa-floppy-disk',
  'fa-regular fa-file-zipper',
  'fa-regular fa-file-video',
  'fa-regular fa-file-powerpoint',
  'fa-regular fa-file-lines',
  'fa-regular fa-file-image',
  'fa-regular fa-file-code',
  'fa-regular fa-file-audio',
  'fa-regular fa-face-tired',
  'fa-regular fa-face-surprise',
  'fa-regular fa-face-smile-wink',
  'fa-regular fa-face-smile-beam',
  'fa-regular fa-face-sad-tear',
  'fa-regular fa-face-sad-cry',
  'fa-regular fa-face-rolling-eyes',
  'fa-regular fa-face-meh-blank',
  'fa-regular fa-face-meh',
  'fa-regular fa-face-laugh-wink',
  'fa-regular fa-face-laugh-squint',
  'fa-regular fa-face-laugh-beam',
  'fa-regular fa-face-laugh',
  'fa-regular fa-face-kiss-wink-heart',
  'fa-regular fa-face-kiss-beam',
  'fa-regular fa-face-kiss',
  'fa-regular fa-face-grin-wink',
  'fa-regular fa-face-grin-wide',
  'fa-regular fa-face-grin-tongue-wink',
  'fa-regular fa-face-grin-tongue-squint',
  'fa-regular fa-face-grin-tongue',
  'fa-regular fa-face-grin-tears',
  'fa-regular fa-face-grin-stars',
  'fa-regular fa-face-grin-squint-tears',
  'fa-regular fa-face-grin-squint',
  'fa-regular fa-face-grin-hearts',
  'fa-regular fa-face-grin-beam-sweat',
  'fa-regular fa-face-grin-beam',
  'fa-regular fa-face-grin',
  'fa-regular fa-face-grimace',
  'fa-regular fa-face-frown-open',
  'fa-regular fa-face-frown',
  'fa-regular fa-face-flushed',
  'fa-regular fa-face-dizzy',
  'fa-regular fa-face-angry',
  'fa-regular fa-envelope-open',
  'fa-regular fa-comment-dots',
  'fa-regular fa-circle-stop',
  'fa-regular fa-circle-right',
  'fa-regular fa-circle-question',
  'fa-regular fa-circle-play',
  'fa-regular fa-circle-pause',
  'fa-regular fa-circle-left',
  'fa-regular fa-circle-dot',
  'fa-regular fa-chess-rook',
  'fa-regular fa-chess-queen',
  'fa-regular fa-chess-pawn',
  'fa-regular fa-chess-knight',
  'fa-regular fa-chess-king',
  'fa-regular fa-chess-bishop',
  'fa-regular fa-chart-bar',
  'fa-regular fa-calendar-xmark',
  'fa-regular fa-calendar-plus',
  'fa-regular fa-calendar-minus',
  'fa-regular fa-calendar-check',
  'fa-regular fa-bell-slash'
] as const;
export const brand = [

  // brand
  'fa-brands fa-facebook',
  'fa-brands fa-twitter',
  'fa-brands fa-instagram',
  'fa-brands fa-tiktok',
  'fa-brands fa-linkedin',
  'fa-brands fa-github',
  'fa-brands fa-discord',
  'fa-brands fa-youtube',
  'fa-brands fa-wordpress',
  'fa-brands fa-slack',
  'fa-brands fa-figma',
  'fa-brands fa-apple',
  'fa-brands fa-google',
  'fa-brands fa-stripe',
  'fa-brands fa-algolia',
  'fa-brands fa-docker',
  'fa-brands fa-windows',
  'fa-brands fa-paypal',
  'fa-brands fa-stack-overflow',
  'fa-brands fa-kickstarter',
  'fa-brands fa-dribbble',
  'fa-brands fa-dropbox',
  'fa-brands fa-squarespace',
  'fa-brands fa-android',
  'fa-brands fa-shopify',
  'fa-brands fa-medium',
  'fa-brands fa-codepen',
  'fa-brands fa-cloudflare',
  'fa-brands fa-airbnb',
  'fa-brands fa-vimeo',
  'fa-brands fa-whatsapp',
  'fa-brands fa-intercom',
  'fa-brands fa-usps',
  'fa-brands fa-wix',
  'fa-brands fa-line',
  'fa-brands fa-behance',
  'fa-brands fa-openid',
  'fa-brands fa-product-hunt',
  'fa-brands fa-internet-explorer',
  'fa-brands fa-pagelines',
  'fa-brands fa-teamspeak',
  'fa-brands fa-html5',
  'fa-brands fa-telegram',
  'fa-brands fa-pinterest',
  'fa-brands fa-dashcube',
  'fa-brands fa-ideal',
  'fa-brands fa-salesforce',
  'fa-brands fa-readme',
  'fa-brands fa-free-code-camp',
  'fa-brands fa-soundcloud',
  'fa-brands fa-square-twitter',
  'fa-brands fa-accessible-icon',
  'fa-brands fa-cc-visa',
  'fa-brands fa-goodreads-g',
  'fa-brands fa-google-play',
  'fa-brands fa-react',
  'fa-brands fa-wikipedia-w',
  'fa-brands fa-square-js',
  'fa-brands fa-java',
  'fa-brands fa-square-pinterest',
  'fa-brands fa-python',
  'fa-brands fa-skype',
  'fa-brands fa-linux',
  'fa-brands fa-node',
  'fa-brands fa-rebel',
  'fa-brands fa-etsy',
  'fa-brands fa-discourse',
  'fa-brands fa-amazon',
  'fa-brands fa-glide-g',
  'fa-brands fa-gitlab',
  'fa-brands fa-spotify',
  'fa-brands fa-think-peaks',
  'fa-brands fa-microsoft',
  'fa-brands fa-elementor',
  'fa-brands fa-pied-piper',
  'fa-brands fa-square-youtube',
  'fa-brands fa-cc-mastercard',
  'fa-brands fa-facebook-messenger',
  'fa-brands fa-atlassian',
  'fa-brands fa-playstation',
  'fa-brands fa-fly',
  'fa-brands fa-meetup',
  'fa-brands fa-twitch',
  'fa-brands fa-waze',
  'fa-brands fa-zhihu',
  'fa-brands fa-yoast',
  'fa-brands fa-yelp',
  'fa-brands fa-yarn',
  'fa-brands fa-yandex-international',
  'fa-brands fa-yandex',
  'fa-brands fa-yammer',
  'fa-brands fa-yahoo',
  'fa-brands fa-y-combinator',
  'fa-brands fa-xing',
  'fa-brands fa-xbox',
  'fa-brands fa-wpressr',
  'fa-brands fa-wpforms',
  'fa-brands fa-wpexplorer',
  'fa-brands fa-wpbeginner',
  'fa-brands fa-wordpress-simple',
  'fa-brands fa-wolf-pack-battalion',
  'fa-brands fa-wodu',
  'fa-brands fa-wizards-of-the-coast',
  'fa-brands fa-wirsindhandwerk',
  'fa-brands fa-whmcs',
  'fa-brands fa-weixin',
  'fa-brands fa-weibo',
  'fa-brands fa-weebly',
  'fa-brands fa-watchman-monitoring',
  'fa-brands fa-vuejs',
  'fa-brands fa-vnv',
  'fa-brands fa-vk',
  'fa-brands fa-vine',
  'fa-brands fa-vimeo-v',
  'fa-brands fa-viber',
  'fa-brands fa-viadeo',
  'fa-brands fa-viacoin',
  'fa-brands fa-vaadin',
  'fa-brands fa-ussunnah',
  'fa-brands fa-usb',
  'fa-brands fa-ups',
  'fa-brands fa-untappd',
  'fa-brands fa-unsplash',
  'fa-brands fa-unity',
  'fa-brands fa-uniregistry',
  'fa-brands fa-uncharted',
  'fa-brands fa-umbraco',
  'fa-brands fa-uikit',
  'fa-brands fa-ubuntu',
  'fa-brands fa-uber',
  'fa-brands fa-typo3',
  'fa-brands fa-tumblr',
  'fa-brands fa-trello',
  'fa-brands fa-trade-federation',
  'fa-brands fa-themeisle',
  'fa-brands fa-themeco',
  'fa-brands fa-the-red-yeti',
  'fa-brands fa-tencent-weibo',
  'fa-brands fa-symfony',
  'fa-brands fa-swift',
  'fa-brands fa-suse',
  'fa-brands fa-supple',
  'fa-brands fa-superpowers',
  'fa-brands fa-stumbleupon-circle',
  'fa-brands fa-stumbleupon',
  'fa-brands fa-studiovinari',
  'fa-brands fa-stripe-s',
  'fa-brands fa-strava',
  'fa-brands fa-sticker-mule',
  'fa-brands fa-steam-symbol',
  'fa-brands fa-steam',
  'fa-brands fa-staylinked',
  'fa-brands fa-stackpath',
  'fa-brands fa-stack-exchange',
  'fa-brands fa-square-xing',
  'fa-brands fa-square-whatsapp',
  'fa-brands fa-square-vimeo',
  'fa-brands fa-square-viadeo',
  'fa-brands fa-square-tumblr',
  'fa-brands fa-square-steam',
  'fa-brands fa-square-snapchat',
  'fa-brands fa-square-reddit',
  'fa-brands fa-square-pied-piper',
  'fa-brands fa-square-odnoklassniki',
  'fa-brands fa-square-lastfm',
  'fa-brands fa-square-instagram',
  'fa-brands fa-square-hacker-news',
  'fa-brands fa-square-google-plus',
  'fa-brands fa-square-gitlab',
  'fa-brands fa-square-github',
  'fa-brands fa-square-git',
  'fa-brands fa-square-font-awesome-stroke',
  'fa-brands fa-square-font-awesome',
  'fa-brands fa-square-facebook',
  'fa-brands fa-square-dribbble',
  'fa-brands fa-square-behance',
  'fa-brands fa-speaker-deck',
  'fa-brands fa-speakap',
  'fa-brands fa-space-awesome',
  'fa-brands fa-sourcetree',
  'fa-brands fa-snapchat',
  'fa-brands fa-slideshare',
  'fa-brands fa-skyatlas',
  'fa-brands fa-sketch',
  'fa-brands fa-sitrox',
  'fa-brands fa-sith',
  'fa-brands fa-sistrix',
  'fa-brands fa-simplybuilt',
  'fa-brands fa-shopware',
  'fa-brands fa-shirtsinbulk',
  'fa-brands fa-servicestack',
  'fa-brands fa-sellsy',
  'fa-brands fa-sellcast',
  'fa-brands fa-searchengin',
  'fa-brands fa-scribd',
  'fa-brands fa-screenpal',
  'fa-brands fa-schlix',
  'fa-brands fa-sass',
  'fa-brands fa-safari',
  'fa-brands fa-rust',
  'fa-brands fa-rockrms',
  'fa-brands fa-rocketchat',
  'fa-brands fa-rev',
  'fa-brands fa-resolving',
  'fa-brands fa-researchgate',
  'fa-brands fa-replyd',
  'fa-brands fa-renren',
  'fa-brands fa-redhat',
  'fa-brands fa-reddit-alien',
  'fa-brands fa-reddit',
  'fa-brands fa-red-river',
  'fa-brands fa-reacteurope',
  'fa-brands fa-ravelry',
  'fa-brands fa-raspberry-pi',
  'fa-brands fa-r-project',
  'fa-brands fa-quora',
  'fa-brands fa-quinscape',
  'fa-brands fa-qq',
  'fa-brands fa-pushed',
  'fa-brands fa-pix',
  'fa-brands fa-pinterest-p',
  'fa-brands fa-pied-piper-pp',
  'fa-brands fa-pied-piper-hat',
  'fa-brands fa-pied-piper-alt',
  'fa-brands fa-php',
  'fa-brands fa-phoenix-squadron',
  'fa-brands fa-phoenix-framework',
  'fa-brands fa-phabricator',
  'fa-brands fa-periscope',
  'fa-brands fa-perbyte',
  'fa-brands fa-patreon',
  'fa-brands fa-palfed',
  'fa-brands fa-page4',
  'fa-brands fa-padlet',
  'fa-brands fa-osi',
  'fa-brands fa-orcid',
  'fa-brands fa-optin-monster',
  'fa-brands fa-opera',
  'fa-brands fa-opencart',
  'fa-brands fa-old-republic',
  'fa-brands fa-odnoklassniki',
  'fa-brands fa-octopus-deploy',
  'fa-brands fa-nutritionix',
  'fa-brands fa-ns8',
  'fa-brands fa-npm',
  'fa-brands fa-node-js',
  'fa-brands fa-nimblr',
  'fa-brands fa-nfc-symbol',
  'fa-brands fa-nfc-directional',
  'fa-brands fa-neos',
  'fa-brands fa-napster',
  'fa-brands fa-monero',
  'fa-brands fa-modx',
  'fa-brands fa-mizuni',
  'fa-brands fa-mixer',
  'fa-brands fa-mixcloud',
  'fa-brands fa-mix',
  'fa-brands fa-microblog',
  'fa-brands fa-meta',
  'fa-brands fa-mendeley',
  'fa-brands fa-megaport',
  'fa-brands fa-medrt',
  'fa-brands fa-medapps',
  'fa-brands fa-mdb',
  'fa-brands fa-maxcdn',
  'fa-brands fa-mastodon',
  'fa-brands fa-markdown',
  'fa-brands fa-mandalorian',
  'fa-brands fa-mailchimp',
  'fa-brands fa-magento',
  'fa-brands fa-lyft',
  'fa-brands fa-linode',
  'fa-brands fa-linkedin-in',
  'fa-brands fa-less',
  'fa-brands fa-leanpub',
  'fa-brands fa-lastfm',
  'fa-brands fa-laravel',
  'fa-brands fa-korvue',
  'fa-brands fa-kickstarter-k',
  'fa-brands fa-keycdn',
  'fa-brands fa-keybase',
  'fa-brands fa-kaggle',
  'fa-brands fa-jsfiddle',
  'fa-brands fa-js',
  'fa-brands fa-joomla',
  'fa-brands fa-joget',
  'fa-brands fa-jira',
  'fa-brands fa-jenkins',
  'fa-brands fa-jedi-order',
  'fa-brands fa-itunes-note',
  'fa-brands fa-itunes',
  'fa-brands fa-itch-io',
  'fa-brands fa-ioxhost',
  'fa-brands fa-invision',
  'fa-brands fa-instalod',
  'fa-brands fa-imdb',
  'fa-brands fa-hubspot',
  'fa-brands fa-houzz',
  'fa-brands fa-hotjar',
  'fa-brands fa-hornbill',
  'fa-brands fa-hooli',
  'fa-brands fa-hive',
  'fa-brands fa-hire-a-helper',
  'fa-brands fa-hips',
  'fa-brands fa-hashnode',
  'fa-brands fa-hackerrank',
  'fa-brands fa-hacker-news',
  'fa-brands fa-gulp',
  'fa-brands fa-guilded',
  'fa-brands fa-grunt',
  'fa-brands fa-gripfire',
  'fa-brands fa-grav',
  'fa-brands fa-gratipay',
  'fa-brands fa-google-wallet',
  'fa-brands fa-google-plus-g',
  'fa-brands fa-google-plus',
  'fa-brands fa-google-pay',
  'fa-brands fa-google-drive',
  'fa-brands fa-goodreads',
  'fa-brands fa-golang',
  'fa-brands fa-gofore',
  'fa-brands fa-glide',
  'fa-brands fa-gitter',
  'fa-brands fa-gitkraken',
  'fa-brands fa-github-alt',
  'fa-brands fa-git-alt',
  'fa-brands fa-git',
  'fa-brands fa-gg-circle',
  'fa-brands fa-gg',
  'fa-brands fa-get-pocket',
  'fa-brands fa-galactic-senate',
  'fa-brands fa-galactic-republic',
  'fa-brands fa-fulcrum',
  'fa-brands fa-freebsd',
  'fa-brands fa-foursquare',
  'fa-brands fa-forumbee',
  'fa-brands fa-fort-awesome-alt',
  'fa-brands fa-fort-awesome',
  'fa-brands fa-fonticons-fi',
  'fa-brands fa-fonticons',
  'fa-brands fa-font-awesome',
  'fa-brands fa-flipboard',
  'fa-brands fa-flickr',
  'fa-brands fa-firstdraft',
  'fa-brands fa-first-order-alt',
  'fa-brands fa-first-order',
  'fa-brands fa-firefox-browser',
  'fa-brands fa-firefox',
  'fa-brands fa-fedora',
  'fa-brands fa-fedex',
  'fa-brands fa-fantasy-flight-games',
  'fa-brands fa-facebook-f',
  'fa-brands fa-expeditedssl',
  'fa-brands fa-evernote',
  'fa-brands fa-ethereum',
  'fa-brands fa-erlang',
  'fa-brands fa-envira',
  'fa-brands fa-empire',
  'fa-brands fa-ember',
  'fa-brands fa-ello',
  'fa-brands fa-edge-legacy',
  'fa-brands fa-edge',
  'fa-brands fa-ebay',
  'fa-brands fa-earlybirds',
  'fa-brands fa-dyalog',
  'fa-brands fa-drupal',
  'fa-brands fa-draft2digital',
  'fa-brands fa-dochub',
  'fa-brands fa-digital-ocean',
  'fa-brands fa-digg',
  'fa-brands fa-diaspora',
  'fa-brands fa-dhl',
  'fa-brands fa-deviantart',
  'fa-brands fa-dev',
  'fa-brands fa-deskpro',
  'fa-brands fa-deploydog',
  'fa-brands fa-delicious',
  'fa-brands fa-deezer',
  'fa-brands fa-dailymotion',
  'fa-brands fa-d-and-d-beyond',
  'fa-brands fa-d-and-d',
  'fa-brands fa-cuttlefish',
  'fa-brands fa-css3-alt',
  'fa-brands fa-css3',
  'fa-brands fa-critical-role',
  'fa-brands fa-creative-commons-zero',
  'fa-brands fa-creative-commons-share',
  'fa-brands fa-creative-commons-sampling-plus',
  'fa-brands fa-creative-commons-sampling',
  'fa-brands fa-creative-commons-sa',
  'fa-brands fa-creative-commons-remix',
  'fa-brands fa-creative-commons-pd-alt',
  'fa-brands fa-creative-commons-pd',
  'fa-brands fa-creative-commons-nd',
  'fa-brands fa-creative-commons-nc-jp',
  'fa-brands fa-creative-commons-nc-eu',
  'fa-brands fa-creative-commons-nc',
  'fa-brands fa-creative-commons-by',
  'fa-brands fa-creative-commons',
  'fa-brands fa-cpanel',
  'fa-brands fa-cotton-bureau',
  'fa-brands fa-contao',
  'fa-brands fa-connectdevelop',
  'fa-brands fa-confluence',
  'fa-brands fa-codiepie',
  'fa-brands fa-cmplid',
  'fa-brands fa-cloudversify',
  'fa-brands fa-cloudsmith',
  'fa-brands fa-cloudscale',
  'fa-brands fa-chromecast',
  'fa-brands fa-chrome',
  'fa-brands fa-centos',
  'fa-brands fa-centercode',
  'fa-brands fa-cc-stripe',
  'fa-brands fa-cc-paypal',
  'fa-brands fa-cc-jcb',
  'fa-brands fa-cc-discover',
  'fa-brands fa-cc-diners-club',
  'fa-brands fa-cc-apple-pay',
  'fa-brands fa-cc-amex',
  'fa-brands fa-cc-amazon-pay',
  'fa-brands fa-canadian-maple-leaf',
  'fa-brands fa-buysellads',
  'fa-brands fa-buy-n-large',
  'fa-brands fa-buromobelexperte',
  'fa-brands fa-buffer',
  'fa-brands fa-btc',
  'fa-brands fa-bots',
  'fa-brands fa-bootstrap',
  'fa-brands fa-bluetooth-b',
  'fa-brands fa-bluetooth',
  'fa-brands fa-blogger-b',
  'fa-brands fa-blogger',
  'fa-brands fa-blackberry',
  'fa-brands fa-black-tie',
  'fa-brands fa-bity',
  'fa-brands fa-bitcoin',
  'fa-brands fa-bitbucket',
  'fa-brands fa-bimobject',
  'fa-brands fa-bilibili',
  'fa-brands fa-battle-net',
  'fa-brands fa-bandcamp',
  'fa-brands fa-aws',
  'fa-brands fa-aviato',
  'fa-brands fa-avianex',
  'fa-brands fa-autoprefixer',
  'fa-brands fa-audible',
  'fa-brands fa-asymmetrik',
  'fa-brands fa-artstation',
  'fa-brands fa-apple-pay',
  'fa-brands fa-apper',
  'fa-brands fa-app-store-ios',
  'fa-brands fa-app-store',
  'fa-brands fa-angular',
  'fa-brands fa-angrycreative',
  'fa-brands fa-angellist',
  'fa-brands fa-amilia',
  'fa-brands fa-amazon-pay',
  'fa-brands fa-alipay',
  'fa-brands fa-affiliatetheme',
  'fa-brands fa-adversal',
  'fa-brands fa-adn',
  'fa-brands fa-accusoft',
  'fa-brands fa-500px',
  'fa-brands fa-42-group'
] as const;

export const list = [ ...solid, ...regular, ...brand ] as const;

type Icon = typeof list[number];

export default Icon;
